name: Unit Tests

on: [push]

jobs:
  docker-unit-tests:
    runs-on: ubuntu-latest
    name: Build and run unit tests Docker image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t unit-test-image -f Dockerfile .

      - name: Run image
        run: docker run --rm unit-test-image